### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getElementsByClassName')

### ISSUE THREAD

**Issue by jonwaland** [Mariusthvdb/custom-ui#107]
Home Assistant 2023.9.3
Frontend 20230911.0 - latest

```
2023-09-26 15:31:10.967 ERROR (MainThread) [frontend.js.latest.202309110] Uncaught error from Chrome 117.0.0.0 on Windows 10
2023-09-26 15:31:10.967 ERROR (MainThread) [frontend.js.latest.202309110] Uncaught error from Chrome 117.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'getElementsByClassName')
updateMoreInfo (/hacsfiles/custom-ui/custom-ui.js:54:7)
dispatchEvent (src/common/dom/fire_event.ts:76:7)
nextRender (src/components/ha-expansion-panel.ts:131:14)
```

No idea what I was doing, and not seen this before.

From chrome console:

```
Uncaught TypeError: Cannot read properties of null (reading 'getElementsByClassName')
    at updateMoreInfo (custom-ui.js?hacstag=26755814820230908:54:7)
    at o (fire_event.ts:76:8)
    at i.value (ha-expansion-panel.ts:131:5)
```

Feel free to close if not enough info

**Comment by Mariusthvdb** [comment]
When does this happen? And where? On any card or only specific?

Does it occur when clicking the dropdown or upon opening the more info ?

**Comment by jonwaland** [comment]
I have absolutely no idea what triggered it!

I've just been on every tab/dashboard/screen I can on my installation. clicked on more info on many cards. added a new history-explorer card (I dont use it). 

cant trigger it! So I'll close for now.
